version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  general-testing:
    jobs:
      - build
  unit-tests:
    jobs:
      - unit-tests

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\vIDsafe
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: "Install project dependencies"
          command: msbuild -t:restore -p:RestorePackagesConfig=true
      - run:
          name: "Run Build step"
          command: msbuild ..\vIDsafe.UnitTests\vIDsafe.UnitTests.csproj /p:Configuration=Release
      - store_artifacts:
          path: ..\vIDsafe.UnitTests\bin\Release\vIDsafe.UnitTests.exe
      - run:
          name: Run master account tests
          command: |
              cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\extensions\TestPlatform"
              .\vstest.console.exe "C:\Users\circleci\project\vIDsafe.UnitTests\bin\Release\vIDsafe.UnitTests.dll"

  unit-tests:
    executor:
      name: win/default
    steps:     
      - checkout
      - run:
          name: Run master account tests
          command: |
              cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\extensions\TestPlatform"
              .\vstest.console.exe "C:\Users\circleci\project\vIDsafe.UnitTests\bin\Release\vIDsafe.UnitTests.dll"
